In [26]:
#creating array
import array
arr=array.array("I",[2,4,6,8,10,12])
print("New created array.",end="\r")
for I in range(0,5):
  print(arr[I],end="\r")
  print("\r")


In [28]:
#importing pandas as pd
import pandas as pd
dict={"name":["Pratik","Shivansh","Anak","Rini"],
'age':["20","39","34","36"]}
info=pd.DataFrame(dict,index=[True,True,False,True])
print(info)

           name age
True     Pratik  20
True   Shivansh  39
False      Anak  34
True       Rini  36


In [37]:
#Example 2:
                   #importing pandas as pd
import pandas as pd
                   #dictionary of lists
dict={'name':["Pratik","Anak","Rini","Shivansh"],
'age':["28","39","34","36"]}
info=pd.DataFrame(dict,index=[True,True,False,True])
                   #accessing a dataframe using loc[]function
print(info.loc[True])

          name age
True    Pratik  28
True      Anak  39
True  Shivansh  36


In [45]:
#reshaped parameter
import numpy as np
arr=np.arange(16)
print("The Original array is:\n",arr)
         #shape array with 2 rows and 8 columns
arr = np.arange(16).reshape(2,8)
print("\nreshaped array:\n",arr)
arr= np.arange(16).reshape(8,2)
print("\nreshaped array: \n",arr)


The Original array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshaped array:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

reshaped array: 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
